/*
 * ocl_error.c
 *
 *  Created on: Nov 11, 2013
 *      Author: tcarstens
 */


#include <stdio.h>
#include "ocl_error.h"


#define CASE(e) case e: ret = #e; break;

const char *ocl_error_str(cl_int err) {
	const char *ret = "UNKNOWN_ERROR";

	switch (err) {
	CASE(CL_SUCCESS)
	CASE(CL_INVALID_VALUE)
	CASE(CL_INVALID_PLATFORM)
	CASE(CL_INVALID_DEVICE)
	CASE(CL_DEVICE_NOT_AVAILABLE)
	CASE(CL_OUT_OF_HOST_MEMORY)
	CASE(CL_INVALID_QUEUE_PROPERTIES)
	CASE(CL_INVALID_PROGRAM)
	CASE(CL_INVALID_PROGRAM_EXECUTABLE)
	CASE(CL_INVALID_KERNEL_NAME)
	CASE(CL_INVALID_KERNEL_DEFINITION)
	CASE(CL_INVALID_KERNEL)
	CASE(CL_INVALID_ARG_INDEX)
	CASE(CL_INVALID_ARG_VALUE)
	CASE(CL_INVALID_MEM_OBJECT)
	CASE(CL_INVALID_OPERATION)
	CASE(CL_COMPILER_NOT_AVAILABLE)
	CASE(CL_MEM_OBJECT_ALLOCATION_FAILURE)
	CASE(CL_BUILD_PROGRAM_FAILURE)
	CASE(CL_INVALID_BINARY)
	CASE(CL_INVALID_ARG_SIZE)
	CASE(CL_OUT_OF_RESOURCES)
	default:
		fprintf(stderr, "Unknown error %d\n", err);
	}

	return ret;
}
