/*
 * AUTOGENERATED tcarstens January 2014
 */
#include "tests.h"


#if TEST_SET & TEST_192
#define mpz_set_ul  mpz_set_ocl_ul192

#define ul_bitsize  (192)
#define ul          ocl_ul192


#define ul_test_all        ul192_test_all
#define ul_test_setup      ul192_test_setup
#define ul_test_clear      ul192_test_clear
#define ul_test_run_kernel ul192_test_run_kernel

#define ul_rand_seed_two   "kern_ul192_rand_seed_two"
#define ul_rand_seed_three "kern_ul192_rand_seed_three"

#define ul_binop_test      ul192_binop_test
#define ul_add_test        "kern_ul192_add_test"
#define ul_sub_test        "kern_ul192_sub_test"
#define ul_mul_test        "kern_ul192_mul_test"

#define ul_divremop_test   ul192_divremop_test
#define ul_divrem_test     "kern_ul192_divrem_test"

#define ul_compare_test    ul192_compare_test
#define ul_cmp_test        "kern_ul192_cmp_test"
#define ul_cmp_ui_test     "kern_ul192_cmp_ui_test"

#define ul_mod_binop_test  mod192_binop_test
#define ul_mod_add_test    "kern_mod192_add_test"
#define ul_mod_sub_test    "kern_mod192_sub_test"
#define ul_mod_mul_test    "kern_mod192_mul_test"
#define ul_mod_mul_test2   "kern_mod192_mul_test2"
#define ul_mod_inv_test    "kern_mod192_inv_test"



#define ul_pm1pp1_reorder      "kern_ul192_pm1pp1_reorder"

#define ul_pm1op_test      ul192_pm1op_test
#define ul_pm1_stage1      "kern_ul192_pm1_stage1"
#define ul_pm1_stage2      "kern_ul192_pm1_stage2"

#define ul_pp1op_test      ul192_pp1op_test
#define ul_pp1_stage1      "kern_ul192_pp1_stage1"
#define ul_pp1_stage2      "kern_ul192_pp1_stage2"

#define ul_ecmop_test      ul192_ecmop_test
#define ul_ecm_reorder     "kern_ul192_ecm_reorder"
#define ul_ecm_stage1      "kern_ul192_ecm_stage1"
#define ul_ecm_stage2      "kern_ul192_ecm_stage2"


#include "test_all.h"
#endif /* TEST_192 */
