/*
 * AUTOGENERATED tcarstens January 2014
 */
#include "tests.h"


#if TEST_SET & TEST_64
#define mpz_set_ul  mpz_set_ocl_ul64

#define ul_bitsize  (64)
#define ul          ocl_ul64


#define ul_test_all        ul64_test_all
#define ul_test_setup      ul64_test_setup
#define ul_test_clear      ul64_test_clear
#define ul_test_run_kernel ul64_test_run_kernel

#define ul_rand_seed_two   "kern_ul64_rand_seed_two"
#define ul_rand_seed_three "kern_ul64_rand_seed_three"

#define ul_binop_test      ul64_binop_test
#define ul_add_test        "kern_ul64_add_test"
#define ul_sub_test        "kern_ul64_sub_test"
#define ul_mul_test        "kern_ul64_mul_test"

#define ul_divremop_test   ul64_divremop_test
#define ul_divrem_test     "kern_ul64_divrem_test"

#define ul_compare_test    ul64_compare_test
#define ul_cmp_test        "kern_ul64_cmp_test"
#define ul_cmp_ui_test     "kern_ul64_cmp_ui_test"

#define ul_mod_binop_test  mod64_binop_test
#define ul_mod_add_test    "kern_mod64_add_test"
#define ul_mod_sub_test    "kern_mod64_sub_test"
#define ul_mod_mul_test    "kern_mod64_mul_test"
#define ul_mod_mul_test2   "kern_mod64_mul_test2"
#define ul_mod_inv_test    "kern_mod64_inv_test"



#define ul_pm1pp1_reorder      "kern_ul64_pm1pp1_reorder"

#define ul_pm1op_test      ul64_pm1op_test
#define ul_pm1_stage1      "kern_ul64_pm1_stage1"
#define ul_pm1_stage2      "kern_ul64_pm1_stage2"

#define ul_pp1op_test      ul64_pp1op_test
#define ul_pp1_stage1      "kern_ul64_pp1_stage1"
#define ul_pp1_stage2      "kern_ul64_pp1_stage2"

#define ul_ecmop_test      ul64_ecmop_test
#define ul_ecm_reorder     "kern_ul64_ecm_reorder"
#define ul_ecm_stage1      "kern_ul64_ecm_stage1"
#define ul_ecm_stage2      "kern_ul64_ecm_stage2"


#include "test_all.h"
#endif /* TEST_64 */
