/*
 * AUTOGENERATED tcarstens January 2014
 */
#include "tests.h"


#if TEST_SET & TEST_160
#define mpz_set_ul  mpz_set_ocl_ul160

#define ul_bitsize  (160)
#define ul          ocl_ul160


#define ul_test_all        ul160_test_all
#define ul_test_setup      ul160_test_setup
#define ul_test_clear      ul160_test_clear
#define ul_test_run_kernel ul160_test_run_kernel

#define ul_rand_seed_two   "kern_ul160_rand_seed_two"
#define ul_rand_seed_three "kern_ul160_rand_seed_three"

#define ul_binop_test      ul160_binop_test
#define ul_add_test        "kern_ul160_add_test"
#define ul_sub_test        "kern_ul160_sub_test"
#define ul_mul_test        "kern_ul160_mul_test"

#define ul_divremop_test   ul160_divremop_test
#define ul_divrem_test     "kern_ul160_divrem_test"

#define ul_compare_test    ul160_compare_test
#define ul_cmp_test        "kern_ul160_cmp_test"
#define ul_cmp_ui_test     "kern_ul160_cmp_ui_test"

#define ul_mod_binop_test  mod160_binop_test
#define ul_mod_add_test    "kern_mod160_add_test"
#define ul_mod_sub_test    "kern_mod160_sub_test"
#define ul_mod_mul_test    "kern_mod160_mul_test"
#define ul_mod_mul_test2   "kern_mod160_mul_test2"
#define ul_mod_inv_test    "kern_mod160_inv_test"



#define ul_pm1pp1_reorder      "kern_ul160_pm1pp1_reorder"

#define ul_pm1op_test      ul160_pm1op_test
#define ul_pm1_stage1      "kern_ul160_pm1_stage1"
#define ul_pm1_stage2      "kern_ul160_pm1_stage2"

#define ul_pp1op_test      ul160_pp1op_test
#define ul_pp1_stage1      "kern_ul160_pp1_stage1"
#define ul_pp1_stage2      "kern_ul160_pp1_stage2"

#define ul_ecmop_test      ul160_ecmop_test
#define ul_ecm_reorder     "kern_ul160_ecm_reorder"
#define ul_ecm_stage1      "kern_ul160_ecm_stage1"
#define ul_ecm_stage2      "kern_ul160_ecm_stage2"


#include "test_all.h"
#endif /* TEST_160 */
