/*
 * AUTOGENERATED tcarstens January 2014
 */
#define BITSIZE            (128)


#define ul_ocl             ocl_ul128
#define ul_init_ocl        ocl_ul128_init
#define ul_clear_ocl       ocl_ul128_clear
#define mpz_set_ul_ocl     mpz_set_ocl_ul128
#define mpz_get_ul_ocl     mpz_get_ocl_ul128


#define pm1_process_ocl    pm1_ul128_process_ocl
#define kern_pm1_stage1    "kern_pm1_ul128_stage1"
#define kern_pm1_reorder   "kern_pm1_ul128_reorder"
#define kern_pm1_stage2    "kern_pm1_ul128_stage2"

#define pp1_process_ocl    pp1_ul128_process_ocl
#define kern_pp1_stage1    "kern_pp1_ul128_stage1"
#define kern_pp1_reorder   "kern_pp1_ul128_reorder"
#define kern_pp1_stage2    "kern_pp1_ul128_stage2"

#define ecm_process_ocl    ecm_ul128_process_ocl
#define kern_ecm_stage1    "kern_ecm_ul128_stage1"
#define kern_ecm_reorder   "kern_ecm_ul128_reorder"
#define kern_ecm_stage2    "kern_ecm_ul128_stage2"


#define ellM_point_t       ellM128_point_t
#define mod                mod128
#define ul                 ul128
#define ul_init            ul128_init
#define ul_clear           ul128_clear
#define ul_set_ui          ul128_set_ui
#define ul_cmp_ui          ul128_cmp_ui
#define ul_cmp             ul128_cmp
#define mod_init           mod128_init
#define mod_clear          mod128_clear
#define mod_set            mod128_set
#define mpz_get_ul         mpz_get_ul128
#define mpz_set_ul         mpz_set_ul128
#define pm1_stage1_ul      pm1_stage1_ul128
#define pm1_stage2_ul      pm1_stage2_ul128
#define pp1_stage1_ul      pp1_stage1_ul128
#define pp1_stage2_ul      pp1_stage2_ul128
#define ecm_stage1_ul      ecm_stage1_ul128
#define ecm_stage2_ul      ecm_stage2_ul128


#include "ocl_process_common.h"
